version: '3.8'

services:
  todo-frontend-dev:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 3001:3001
    container_name: todo-frontend-dev
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse_proxy
  redis:
    extends: 
      file: ./todo-backend/docker-compose.dev.yml
      service: redis
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis
  mongo:
    extends:
      file: ./todo-backend/docker-compose.dev.yml
      service: mongo
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    container_name: mongo
  todo-backend-dev:
    extends:
      file: ./todo-backend/docker-compose.dev.yml
      service: todo-backend-dev
    container_name: todo-backend-dev
